name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 3.138.213.181 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh bitnami@3.138.213.181 << 'EOF'
            cd /home/bitnami/assess-landing-page
            git pull origin main
            npm install
            npm run build
            npm run export
            pm2 stop assess-landing-page || true
            pm2 delete assess-landing-page || true
            pm2 start npx --name assess-landing-page -- serve out
            pm2 save
          EOF
